baseURL = 'https://example.org/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Ignacio Illanes Bequer'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpeg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-s"

  # Description to display on homepage
  description = "Design, develop, disrupt."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = false

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "techblog", "Ignacio", "Illanes", "Bequer" ]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "Ignacio Illanes Bequer"

[markup]
  [markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files

  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
